routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/home', 'HomeController@index')->name('home');

Route::get('/welcome', function () {
    return view('welcome');
})->name('welcome');

// Route::get('/', function () {
//     if (Auth::check()) {
//         return redirect()->route('home');
//     } else {
//         return redirect()->route('welcome');
//     }
// });


Route::get('/', function () {
    return view('welcome');
    return view('welcome');
});


Auth::routes();

Route::delete('/cart', 'CartController@clear')->name('cart.clear');

Route::resources([
    'subjects' => 'SubjectController',
    'units' => 'UnitController',
    'tickets' => 'TicketController',
    'cart' => 'CartController',
    'users' => 'UserController',
    'categories' => 'CategoryController'
]);

app/Subject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Subject extends Model
{
     use SoftDeletes;

    protected $fillable = ["name", "category_id", "image"];

    public function category()
    {
        return $this->belongsTo('App\Category')
            ->withTrashed();
    }

    public function units()
    {
        return $this->hasMany('App\Unit');
    }
}

app/Http/Controllers/SubjectController.php
<?php

namespace App\Http\Controllers;

use App\Subject;
use App\Category;
use App\Unit;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SubjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::check()) {
            $subjects = Subject::all();
            $category = Category::first();
            foreach ($subjects as $subject) {
                $units = Unit::where('subject_id', $subject->id)->get();
                $availableUnits = Unit::where('status_id', 1)->where('subject_id', $subject->id)->get();
                $subject->available_stocks = count($availableUnits);
                $subject->total_stocks = count($units);
            }
            return view('subjects.index')
                ->with('subjects', $subjects)
                ->with('category', $category);
        } else {
            return abort(403, 'This action is unauthorized.');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Subject::class);
        $categories = Category::all();
        return view('subjects.create')
            ->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Subject::class);


        $validatedData = $request->validate([
            'name' => 'required|unique:subjects,name,NULL,id,deleted_at,NULL',
            'category_id' => 'required|numeric',
            'image' => 'required|image|max:2000'
        ]);
        $subject = new Subject($validatedData);

        $imageName = time() . '.' . $request->image->getClientOriginalExtension();
        $request->image->move(public_path('/images/subjects'), $imageName);
        $subject->image = $imageName;

        $subject->save();
        $subjectAll = Subject::all();
        return redirect(route('subjects.index'))->with('message', "{$subject->name} subject is added successfully!")->with('alert', 'success');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function show(Subject $subject)
    {
        if (Auth::check()) {
            $units = Unit::where('subject_id', $subject->id)->get();
            $availableUnits = Unit::where('status_id', 1)->where('subject_id', $subject->id)->get();
            $subject->available_stocks = count($availableUnits);
            $subject->total_stocks = count($units);
            $subject->save();
            return view('subjects.show')
                ->with('subject', $subject)
                ->with('units', $units);
        } else {
            return abort(403, 'This action is unauthorized.');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function edit(Subject $subject)
    {
         $this->authorize('update', Subject::class);
        return view('subjects.edit')->with('subject', $subject);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Subject $subject)
    {
        $this->authorize('update', $subject);
        $validatedData = $request->validate([
            'name' => 'required|unique:subjects,name,NULL,id,deleted_at,NULL',
            'category_id' => 'required|numeric',
            'image' => 'required|image|max:2000'
        ]);
        $subject->update($validatedData);

        if ($request->hasFile('image')) {
            $imageName = time() . '.' . $request->image->getClientOriginalExtension();
            $request->image->move(public_path('/images/subjects'), $imageName);
            $subject->image = $imageName;
        }

        $subject->save();
        return redirect(route('subjects.index', $subject->id))->with('message', "Subject is updated successfully!")->with('alert', 'info');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function destroy(Subject $subject)
    {
         $this->authorize('delete', $subject);
        $subject->delete();
        return redirect(route('subjects.index'))->with('message', "{$subject->name} subject has been deleted.")->with('alert', 'warning');
    }
}

resources/views/subjects/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-10 col-lg-9 col-md-8 mx-auto p-4">
            {{-- header --}}
            <div class="row">
                <div class="col-12 text-center">
                    <h1 class="text-center lead display-4">
                        Create Subjects
                    </h1>
                </div>
            </div>
            {{-- end header --}}

            {{-- Create item --}}
            <div class="row mt-5">
                <div class="col-12 col-md-6 mx-auto">
                    {{-- form --}}
                    <form action="{{ route('subjects.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <label for="name">Subject name:</label>
                        <input type="text" name="name" id="name"
                            class="
                                form-control
                                form-control-sm
                                @error('name')
									is-invalid
								@enderror
                            "
                        required>
                        @error('name')
                            <small class="d-block invalid-feedback">
                                <strong>{{ $message }}</strong>
                            </small>
                        @enderror

                        <p class="my-3"></p>

                        {{-- item_model_id --}}
                        <label for="category_id">Subject category:</label>
                        <select name="category_id" id="category_id" class="form-control form-control-sm mt">
                            @foreach($categories as $category)
                                <option value="{{ $category->id}}">{{ $category->name}}</option>
                            @endforeach
                        </select>

                        <p class="my-3"></p>

                        {{-- image --}}
                        @include('subjects.partials.form-group',[
                            'name' => 'image',
                            'type' => 'file',
                            'classes' => ['form-control-file', 'form-control-sm']
                        ])

                        <button class="btn btn-md btn-primary mt-2">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                              <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                              <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                          </svg>
                            Create subject
                        </button>
                    </form>
                    {{-- end form --}}
                </div>

            </div>
            {{-- end Create item --}}
        </div>
    </div>
</div>
@endsection

resources/views/subjects/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-10 col-lg-9 col-md-8 mx-auto p-4">
            {{-- header --}}
            <div class="row">
                <div class="col-12 text-center">
                    <h1 class="text-center lead display-4">
                        Edit Subject
                    </h1>
                </div>
            </div>
            {{-- end header --}}

            {{-- edit item --}}
            <div class="row mt-5">
                <div class="col-12 col-md-6 mx-auto">
                    {{-- form --}}
                    <form action="{{ route('subjects.update', $subject->id) }}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        {{-- item name --}}
                        @include('subjects.partials.form-group',[
                            'name' => 'name',
                            'type' => 'text',
                            'classes' => ['form-control'],
                            'required' => "required",
                            'value' => $subject->name
                            ])

                            {{-- item model --}}
                            <div class="form-group">
                                <label for="category">Category</label>
                                <select id="category" name="category" class="form-control" disabled>
                                    <option value="{{$subject->category_id}}">{{$subject->category->name}}</option>
                                </select>
                                <input type="hidden" name="category_id" id="category_id" value="{{$subject->category_id}}">
                            </div>

                            {{-- image --}}
                            @include('subjects.partials.form-group',[
                                'name' => 'image',
                                'type' => 'file',
                                'classes' => ['form-control-file', 'form-control-sm']
                                ])

                                <button class="btn btn-md btn-warning mt-2">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pen" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                      <path fill-rule="evenodd" d="M13.498.795l.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                                  </svg>
                              Edit</button>
                          </form>
                          {{-- end form --}}
                      </div>

                  </div>
                  {{-- end edit item --}}
              </div>
          </div>
      </div>
      @endsection

resources/views/subjects/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-10 col-lg-9 col-md-8 mx-auto p-4">
                {{-- header --}}
                <div class="row">
                    <div class="col-12 text-center">
                        <h1 class="text-center lead display-4">
                            Subjects
                        </h1>
                       
                    </div>
                    @if(count($subjects) === 0)
                        <div class="col-8 mt-4 mx-auto">
                            @include('partials.no-entry-alert', [
                                'title' => 'items'
                            ])
                        </div>
                    @endif
                </div>
                {{-- end header --}}

                {{-- alert message --}}
                @includeWhen(Session::has('message'), 'partials.alert')

                {{-- category list --}}
                <div class="row mt-5">

                    @foreach($subjects as $subject)
                    {{-- card --}}
                    <div class="col-12 col-sm-6 col-md-4">
                        @include('subjects.partials.card')
                    </div>
                    {{-- end card --}}
                    @endforeach


                </div>
                {{-- end category list --}}
            </div>
        </div>
	</div>
@endsection

resources/views/subjects/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container" aria-live="polite" aria-atomic="true">
    {{-- alert message --}}
    @includeWhen(Session::has('message'), 'partials.alert')
    {{-- end of alert message --}}

    <div class="row">
        {{-- item details and create item unit --}}
        <div class="col-12 col-md-4 col-lg-3 mx-auto mb-5 bg-info">
            <img src="{{ secure_asset('images/subjects/' . $subject->image) }}" alt="" class="img-fluid">
            <div class="bottom-border pb-3">
                <h1>{{$subject->name}}</h1>
                <h4>Category: 
                    <span class="badge badge-warning">{{$subject->category->name}}</span></h4>
                <p class="lead mb-2">Stocks Available: {{$subject->available_stocks}} / {{$subject->total_stocks}}</p>
            </div>
            @can('isAdmin')
            @include('subjects.partials.create-unit')
            @endcan
                @can('isAdmin')
                <a href="{{route('subjects.edit', $subject->id)}}" class=" btn btn-sm btn-warning mb-4">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pen" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M13.498.795l.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                  </svg>
                    Edit {{$subject->name}}</a>
                <form action="{{ route('subjects.destroy', $subject->id) }}" method="post" class="d-inline-block w-auto mt-0 mt-md-1">
                    @csrf
                    @method('DELETE')

                    <button class="btn btn-sm btn-danger mb-4">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                          <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                      </svg>
                     Delete {{$subject->name}}</button>
                </form>
                @endcan
        </div>

        {{-- end of item details and create item unit --}}
        <div class="col-12 col-md-6 col-lg-9">
            <div class="row">
                {{-- no units alert --}}
                @if(count($units) === 0)
                <div class="col-8 mt-4 mx-auto">
                    @include('partials.no-entry-alert', [
                    'title' => 'units'
                    ])
                </div>
                @endif
                {{-- end no units alert --}}

                {{-- units section --}}
                @foreach($units as $unit)
                <div class="col-12 col-sm-8 col-md-6 col-lg-4 mb-2">
                    {{-- unit card --}}
                    <div class="card">

                        {{-- <img src="{{ url($unit->image) }}" alt="" class="card-img-top"> --}}
                        {{-- <img src="{{ asset('images/units/' . $unit->image) }}" alt="" class="card-img-top"> --}}
                        <div class="card-body bg-info">
                            <h4 class="card-title">
                                {{ $unit->control_code }}
                            </h4>
                            <h5>Category:
                                <span class="badge badge-warning ">{{$unit->subject->category->name}}</span>
                            </h5>
                            <h5>Subject:
                                <span class="badge color-Item ">{{$unit->subject->name}}</span>
                            </h5>
                            <h5 class="card-text mb-0">
                                Status: <span class="badge
                                                @if($unit->status_id === 1)
                                                    badge-success
                                                @elseif($unit->status_id === 2)
                                                    badge-danger                                               
                                                @endif
                                            ">{{ $unit->unit_status->name }}</span>
                            </h5>
                        </div>
                        <div class="card-footer bg-info text-white">
                            @if($unit->status_id === 1)
                                @include('units.partials.request-btn')
                            @endif
                            @can('isAdmin')
                            @include('units.partials.edit-btn')
                            @include('units.partials.delete-form')
                            @endcan
                        </div>
                    </div>
                    {{-- unit card end --}}
                </div>
                @endforeach
                {{-- units section end --}}
            </div>
        </div>
    </div>
    {{-- toast --}}
    <div style="position: absolute; top: 4rem; right: 1rem;">
        <!-- Then put toasts within -->
        @include('subjects.partials.toast')
    </div>

    {{--  end of toast --}}
</div>

@if(Session::has('show'))
<script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
<script type="text/javascript" src="{{ secure_asset('js/toast.js') }}"></script>
@endif
@endsection